spring.application.name=NexusMart

spring.datasource.url=jdbc:mysql://localhost:3306/mysalessavvy
spring.datasource.username=root
spring.datasource.password=Ankit@12
spring.jpa.hibernate.ddl-auto=update
spring.security.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet. SecurityAutoConfiguration

 # Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=punkod98765@gmail.com
spring.mail.password=dqepzjvdcxvfpmhg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# ===============================
# JWT Configuration
# ===============================
jwt.secret=your-very-long-secure-secret-key-for-production-12345678901234567890
jwt.expiration=3600000

# ===============================
# CORS Configuration
# ===============================
spring.web.cors.allowed-origins=http://localhost:5174
spring.web.cors.allowed-origin-patterns=http://localhost:5174
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=Content-Type,Authorization
spring.web.cors.exposed-headers=*
spring.web.cors.allow-credentials=true
spring.web.cors.max-age=36000

razorpay.key_id=rzp_test_LqWBBDbgwot5lh
razorpay.key_secret=NETk6HP1NzRzufOYZ7KYfDMb
